---
- name: Update Cache
  apt:
    update_cache: yes

- name: Install Nginx
  apt: name=nginx state=latest

- name: "Copy config file"
  copy: 
    src: "./files/default.conf"
    dest: "/etc/nginx/conf.d/"
  notify: restart nginx

- name: "Copy cep.html"
  copy: 
    src: "./files/cep.html"
    dest: "/var/www/html/"
  notify: restart nginx
...